version: '3'

networks:
  devnet:
    driver: bridge

services:
#  nexus:
#   image: klo2k/nexus3
#   #platform: linux/amd64
#   container_name: nexus3
#   ports:
#     - "8081:8081"
#     - "8082:8082"
#   expose:
#     - 8081
#     - 8082
#   networks:
#     - devnet
#   volumes:
#     - ./volume:/nexus-data
#   restart: always

 jenkins:
  image: jenkins/jenkins
  container_name: jenkins
  ports:
    - "8080:8080"
  networks:
    - devnet
  volumes:
    - "$PWD/jenkins:/var/jenkins_home"
    - /var/run/docker.sock:/var/run/docker.sock

 sonarqube:
  image: sonarqube:latest
  ports:
    - "9000:9000"
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar